'use client'

/**
 * Creator Intelligence Workspace — what a creator card in the KOL Directory
 * opens into.
 *
 * Layout follows the brief: a short identity header (cover, avatar, name,
 * verified, tier, categories, platforms, actions), a KPI strip so the headline
 * numbers do not require opening Performance, then the tabs. Overview is the
 * landing tab and answers "is this creator interesting?" in about thirty
 * seconds — an executive summary, not every chart at once.
 *
 * ── What is real and what is not ─────────────────────────────────────────────
 * The commercial roster (`public.kol_directory`) stores identity only. Real
 * here: username, platform, profile URL, avatar, bio, followers, engagement
 * rate, category, tier, verified, last refresh — plus the standings this
 * component asks the API to compute (rank by followers over the roster, rank
 * inside the creator's category, rank by engagement rate among measured rows)
 * and the sibling account on the other platform where one exists.
 *
 * Everything else the brief asks for — reach, views, EMV, growth, audience
 * demographics, content, campaigns, brand fit, AI insights — has no source at
 * all, so it is generated by `@/lib/discover/kolSample` and marked at every
 * figure. The banner states it once; `<SampleTag />` repeats it beside each
 * number so a screenshot of any single card still carries the caveat.
 */

import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { PJ, TOKENS as T, PLATFORM_ICON, Spinner, fmtNum } from './ui'
import { SampleBanner, SampleTag, StatTile, TrendChart, VIZ, VizCard, Row } from './kolViz'
import {
  AiSection, AudienceSection, BrandFitSection, CampaignSection, PerformanceSection,
  ReportSection, platformLabel, type SectionProps,
} from './KolCreatorSections'
import { sampleIntel } from '@/lib/discover/kolSample'
import type { KolCreatorPayload } from '@/lib/discover/kolDirectory'

const TABS = [
  { id: 'overview', label: 'Overview', icon: 'dashboard' },
  { id: 'performance', label: 'Performance', icon: 'insights' },
  { id: 'audience', label: 'Audience Insights', icon: 'group' },
  { id: 'campaigns', label: 'Campaign History', icon: 'campaign' },
  { id: 'brandfit', label: 'Brand Fit', icon: 'handshake' },
  { id: 'ai', label: 'AI Insights', icon: 'auto_awesome' },
  { id: 'report', label: 'Report', icon: 'lab_profile' },
] as const

type TabId = (typeof TABS)[number]['id']

const initialsOf = (u: string) => (u.replace(/[^a-z0-9]/gi, '').slice(0, 2) || '?').toUpperCase()

export default function KolCreatorWorkspace({
  orgId, orgSlug, kolId,
}: { orgId: string; orgSlug: string; kolId: string }) {
  const router = useRouter()
  const [data, setData] = useState<KolCreatorPayload | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [tab, setTab] = useState<TabId>('overview')
  const [fav, setFav] = useState(false)
  const [toast, setToast] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false
    setError(null)
    fetch(`/api/organizations/${orgId}/discover/kol-directory/${kolId}`)
      .then(async r => {
        if (r.ok) return r.json()
        const body = await r.json().catch(() => null)
        throw new Error(body?.detail || body?.error || `HTTP ${r.status}`)
      })
      .then((d: KolCreatorPayload) => { if (!cancelled) setData(d) })
      .catch(e => { if (!cancelled) setError(String(e?.message ?? e)) })
    return () => { cancelled = true }
  }, [orgId, kolId])

  useEffect(() => {
    if (!toast) return
    const t = window.setTimeout(() => setToast(null), 2200)
    return () => window.clearTimeout(t)
  }, [toast])

  /**
   * Seeded from the creator id, so the sampled figures are identical on every
   * render and every reload — placeholder numbers that reshuffle themselves make
   * the screen obviously fake and the screenshots irreproducible.
   */
  const intel = useMemo(() => (data ? sampleIntel(data.creator) : null), [data])

  const backToDirectory = () => router.push(`/organizations/${orgSlug}/discover/kol`)

  if (error) {
    return (
      <div className="p-5 max-w-[1280px] mx-auto">
        <div className="rounded-[16px] border p-8 text-center" style={{ borderColor: T.outline }}>
          <span className="material-symbols-outlined text-[34px]" style={{ color: '#e6b8b8' }}>error</span>
          <p style={{ ...PJ, color: T.t1 }} className="text-[13px] font-extrabold mt-2">Creator gagal dimuat</p>
          <p className="text-[11.5px] mt-1" style={{ color: T.t3 }}>{error}</p>
          <button type="button" onClick={backToDirectory} style={{ ...PJ, color: T.primary }}
            className="text-[11.5px] font-bold mt-3 hover:underline">
            Kembali ke Directory
          </button>
        </div>
      </div>
    )
  }

  if (!data || !intel) return <div className="p-5"><Spinner label="Memuat creator…" /></div>

  const { creator, rank, platforms } = data
  const sectionProps: SectionProps = { creator, rank, platforms, intel }
  const estReach = creator.followers !== null && creator.erPct !== null
    ? Math.round((creator.followers * creator.erPct) / 100)
    : null

  return (
    <div className="p-5 max-w-[1280px] mx-auto">
      <nav aria-label="Breadcrumb" className="flex items-center gap-1 flex-wrap mb-2">
        {[
          { label: 'KOL Intelligence', href: backToDirectory },
          { label: 'Directory', href: backToDirectory },
          { label: `@${creator.username}` },
        ].map((c, i) => (
          <span key={c.label} className="inline-flex items-center gap-1">
            {i > 0 && <span className="material-symbols-outlined text-[13px]" style={{ color: T.outline }}>chevron_right</span>}
            {c.href ? (
              <button type="button" onClick={c.href} style={PJ}
                className="text-[10.5px] font-bold uppercase tracking-widest hover:underline"
                >
                <span style={{ color: T.t4 }}>{c.label}</span>
              </button>
            ) : (
              <span style={{ ...PJ, color: T.t4 }} className="text-[10.5px] font-bold uppercase tracking-widest">
                {c.label}
              </span>
            )}
          </span>
        ))}
      </nav>

      <SampleBanner>
        Database KOL hanya menyimpan identitas roster — username, platform, followers,
        engagement rate, kategori, tier dan status verified. <b>Followers, engagement
        rate, est. reach, peringkat, dan perbandingan platform di halaman ini adalah
        data asli.</b> Angka lain yang bertanda <SampleTag compact /> adalah contoh untuk
        memperlihatkan bentuk halamannya, bukan hasil pengukuran.
      </SampleBanner>

      {/* ── header ── */}
      <div className="rounded-[18px] border overflow-hidden mb-4"
        style={{ borderColor: T.outline, background: VIZ.surface }}>
        <div className="h-[74px]" style={{ background: T.gradient }} />
        <div className="px-4 pb-4 -mt-8">
          <div className="flex items-end gap-3 flex-wrap">
            <div className="w-[72px] h-[72px] rounded-[18px] border-[3px] flex-shrink-0 overflow-hidden flex items-center justify-center"
              style={{ borderColor: VIZ.surface, background: T.gradient }}>
              {creator.avatarUrl
                // eslint-disable-next-line @next/next/no-img-element -- roster avatars come from CDNs not in next.config
                ? <img src={creator.avatarUrl} alt="" className="w-full h-full object-cover" />
                : <span style={{ ...PJ }} className="text-white text-[22px] font-extrabold">
                    {initialsOf(creator.username)}
                  </span>}
            </div>

            <div className="flex-1 min-w-[220px] pb-0.5">
              <div className="flex items-center gap-2 flex-wrap">
                <h1 style={{ ...PJ, color: T.t1 }} className="text-[19px] font-extrabold tracking-[-0.02em]">
                  @{creator.username}
                </h1>
                {creator.verified && (
                  <span style={{ ...PJ, background: '#eaf5ef', color: '#3d8a5f' }}
                    className="inline-flex items-center gap-1 text-[9.5px] font-extrabold px-2 py-0.5 rounded-full">
                    <span className="material-symbols-outlined text-[12px]">verified</span>Verified
                  </span>
                )}
                {creator.tier && (
                  <span style={{ ...PJ, background: T.surfaceVariant, color: T.primaryDeep }}
                    className="text-[9.5px] font-extrabold px-2 py-0.5 rounded-full">
                    {creator.tier}
                  </span>
                )}
                <span style={{ ...PJ, background: '#fdf3e7', color: '#b5761f' }}
                  className="inline-flex items-center gap-1 text-[9.5px] font-extrabold px-2 py-0.5 rounded-full">
                  <span className="material-symbols-outlined text-[11px]">science</span>
                  Available
                  <SampleTag compact />
                </span>
              </div>

              <div className="text-[11.5px] mt-1" style={{ color: T.t3 }}>
                {creator.categories.length ? creator.categories.join(' · ') : 'Kategori belum diisi di roster'}
              </div>
              <div className="text-[11.5px]" style={{ color: T.t4 }}>
                {creator.city || 'Lokasi belum diisi di roster'}
              </div>

              <div className="flex items-center gap-1.5 mt-2 flex-wrap">
                {platforms.map(p => (
                  <a key={p.id} href={p.profileUrl ?? undefined} target="_blank" rel="noopener noreferrer"
                    style={{ ...PJ, borderColor: T.outline, color: T.t2 }}
                    className="inline-flex items-center gap-1.5 h-7 px-2.5 rounded-lg border text-[11px] font-bold hover:bg-[#f9fafb]">
                    <span className="material-symbols-outlined text-[14px]" style={{ color: T.primary }}>
                      {PLATFORM_ICON[p.platform ?? ''] ?? 'public'}
                    </span>
                    {platformLabel(p.platform)}
                    <span style={{ color: T.t4 }} className="tabular-nums">
                      {p.followers === null ? '—' : fmtNum(p.followers)}
                    </span>
                  </a>
                ))}
              </div>
            </div>

            <div className="flex items-center gap-1.5 flex-wrap pb-0.5">
              <HeaderBtn icon={fav ? 'favorite' : 'favorite_border'}
                onClick={() => { setFav(f => !f); setToast(fav ? 'Dihapus dari favorit' : 'Ditambahkan ke favorit') }} />
              <HeaderBtn icon="compare" label="Compare" onClick={() => setToast('Ditambahkan ke compare')} />
              <HeaderBtn icon="add_shopping_cart" label="Add to Campaign" primary
                onClick={() => setToast('Ditambahkan ke campaign')} />
              <HeaderBtn icon="lab_profile" label="Report" onClick={() => setTab('report')} />
            </div>
          </div>
        </div>
      </div>

      {/* ── KPI strip ── */}
      <div className="grid gap-2.5 mb-4" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(150px,1fr))' }}>
        <StatTile label="Followers"
          value={creator.followers === null ? '—' : fmtNum(creator.followers)}
          hint={`#${rank.followersRank.toLocaleString('id-ID')} dari ${rank.rosterTotal.toLocaleString('id-ID')}`} />
        <StatTile label="Engagement Rate"
          value={creator.erPct === null ? 'belum diukur' : `${creator.erPct.toFixed(2)}%`}
          hint={rank.erRank === null
            ? 'tidak masuk peringkat'
            : `#${rank.erRank.toLocaleString('id-ID')} dari ${rank.erMeasuredTotal.toLocaleString('id-ID')} terukur`} />
        <StatTile label="Est. Reach"
          value={estReach === null ? '—' : fmtNum(estReach)}
          hint="followers × ER" />
        <StatTile label="Avg. Views" value={fmtNum(intel.kpi.avgViews)}
          delta={intel.kpi.delta.views} sample />
        <StatTile label="EMV" value={`$${fmtNum(intel.kpi.emvUsd)}`}
          delta={intel.kpi.delta.emv} sample />
      </div>

      {/* ── tabs ── */}
      <div className="flex gap-1 flex-wrap mb-4 pb-2" style={{ borderBottom: `1px solid ${T.outline}` }}>
        {TABS.map(t => (
          <button key={t.id} type="button" onClick={() => setTab(t.id)}
            style={{
              ...PJ,
              background: tab === t.id ? T.surfaceVariant : 'transparent',
              color: tab === t.id ? T.primaryDeep : T.t3,
            }}
            className="inline-flex items-center gap-1.5 h-8 px-3 rounded-lg text-[11.5px] font-bold">
            <span className="material-symbols-outlined text-[15px]">{t.icon}</span>
            {t.label}
          </button>
        ))}
      </div>

      {tab === 'overview' && <OverviewSection {...sectionProps} onGoTo={setTab} />}
      {tab === 'performance' && <PerformanceSection {...sectionProps} />}
      {tab === 'audience' && <AudienceSection {...sectionProps} />}
      {tab === 'campaigns' && <CampaignSection {...sectionProps} />}
      {tab === 'brandfit' && <BrandFitSection {...sectionProps} />}
      {tab === 'ai' && <AiSection {...sectionProps} />}
      {tab === 'report' && <ReportSection {...sectionProps} />}

      {toast && (
        <div style={{ ...PJ, background: T.primaryDeep }}
          className="fixed bottom-5 left-1/2 -translate-x-1/2 text-white text-[11.5px] font-bold px-3.5 py-2 rounded-xl shadow-lg z-50">
          {toast}
        </div>
      )}
    </div>
  )
}

function HeaderBtn({
  icon, label, onClick, primary,
}: { icon: string; label?: string; onClick: () => void; primary?: boolean }) {
  return (
    <button type="button" onClick={onClick} title={label ?? icon}
      style={{
        ...PJ,
        background: primary ? T.primary : VIZ.surface,
        borderColor: primary ? T.primary : T.outline,
        color: primary ? '#fff' : T.t2,
      }}
      className="inline-flex items-center gap-1.5 h-8 px-2.5 rounded-lg border text-[11.5px] font-bold hover:brightness-[.98]">
      <span className="material-symbols-outlined text-[15px]">{icon}</span>
      {label}
    </button>
  )
}

/* ── Overview ─────────────────────────────────────────────────────────────── */

function OverviewSection({
  creator, rank, platforms, intel, onGoTo,
}: SectionProps & { onGoTo: (t: TabId) => void }) {
  const quickLinks = TABS.filter(t => t.id !== 'overview' && t.id !== 'report')

  return (
    <div className="flex flex-col gap-4">
      <div className="grid gap-4" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(300px,1fr))' }}>
        <VizCard title={`About @${creator.username}`}>
          <p className="text-[12.5px] leading-[1.65]" style={{ color: T.t2 }}>
            {creator.bio || (
              <span style={{ color: T.t4 }}>
                Roster tidak menyimpan bio untuk creator ini — terisi hanya untuk sekitar
                12% roster.
              </span>
            )}
          </p>
          <div className="mt-3">
            <Row label="Primary audience" value={<span className="inline-flex items-center gap-1.5">
              {intel.audience.gender[0]?.label} {intel.audience.age[1]?.label}
            </span>} sample />
            <Row label="Creator tier" value={creator.tier ?? '—'} />
            <Row label="Audience authenticity" value={`${intel.audience.authenticity}%`} sample />
          </div>
        </VizCard>

        <VizCard title="Creator Snapshot">
          <Row label="Category" value={creator.categories[0] ?? '—'} />
          <Row label="Niche" value={creator.categories.slice(1).join(' · ') || '—'} />
          <Row label="Tier" value={creator.tier ?? '—'} />
          <Row label="Location" value={creator.city || 'belum diisi'} />
          <Row label="Platforms" value={platforms.map(p => platformLabel(p.platform)).join(' · ')} />
          <Row label="Followers" value={creator.followers === null ? '—' : fmtNum(creator.followers)} />
          <Row label="Engagement" value={creator.erPct === null ? 'belum diukur' : `${creator.erPct.toFixed(2)}%`} />
          <Row label="Growth" value={`${intel.growth.monthly}% / bulan`} sample />
          <Row label="Authenticity" value={`${intel.audience.authenticity}%`} sample />
        </VizCard>
      </div>

      <VizCard title="Performance Snapshot" subtitle="Ringkasan sebelum masuk ke tab Performance">
        <div className="grid gap-2.5" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(140px,1fr))' }}>
          <StatTile label="Engagement"
            value={creator.erPct === null ? 'belum diukur' : `${creator.erPct.toFixed(2)}%`}
            hint="data asli roster" />
          <StatTile label="Reach" value={fmtNum(intel.kpi.avgReach)} delta={intel.kpi.delta.reach} sample />
          <StatTile label="Views" value={fmtNum(intel.kpi.avgViews)} delta={intel.kpi.delta.views} sample />
          <StatTile label="Shares" value={fmtNum(intel.performance.shares)} sample />
        </div>
      </VizCard>

      <VizCard title="Performance Trend" subtitle="Engagement rate — 6 bulan terakhir" sample>
        <TrendChart points={intel.trend.map(p => ({ x: p.month, y: p.erPct }))}
          format={n => `${n.toFixed(2)}%`} label="Engagement rate" />
      </VizCard>

      <div className="grid gap-4" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(300px,1fr))' }}>
        {/* The one insight card built entirely on measured data. */}
        <VizCard title="Quick Insights" subtitle="Dihitung dari peringkat creator ini di roster">
          <ul className="flex flex-col gap-2.5">
            <Insight icon="leaderboard" tone={VIZ.good}
              text={<>Peringkat <b>#{rank.followersRank.toLocaleString('id-ID')}</b> dari{' '}
                {rank.rosterTotal.toLocaleString('id-ID')} creator berdasarkan followers — di atas{' '}
                <b>{rank.followersPercentile}%</b> roster.</>} />
            {rank.categoryName && rank.categoryFollowersRank !== null && (
              <Insight icon="category" tone={VIZ.series}
                text={<>Di kategori <b>{rank.categoryName}</b>, creator ini nomor{' '}
                  <b>#{rank.categoryFollowersRank}</b> dari {rank.categoryTotal.toLocaleString('id-ID')}.</>} />
            )}
            {rank.erRank !== null ? (
              <Insight icon="bolt" tone={rank.erPercentile !== null && rank.erPercentile >= 50 ? VIZ.good : VIZ.warning}
                text={<>Engagement rate <b>{creator.erPct?.toFixed(2)}%</b> — peringkat{' '}
                  <b>#{rank.erRank.toLocaleString('id-ID')}</b> dari{' '}
                  {rank.erMeasuredTotal.toLocaleString('id-ID')} creator yang pernah diukur.</>} />
            ) : (
              <Insight icon="help" tone={T.t4}
                text={<>Engagement rate creator ini belum pernah diukur, jadi tidak bisa
                  dibandingkan dengan roster.</>} />
            )}
            <Insight icon="update" tone={T.t4}
              text={<>Status data <b>{creator.status}</b>
                {creator.lastRefreshedAt && <> · terakhir di-refresh {creator.lastRefreshedAt.slice(0, 10)}</>}.</>} />
          </ul>
        </VizCard>

        <VizCard title="Quick Links">
          <div className="grid gap-1.5" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(140px,1fr))' }}>
            {quickLinks.map(l => (
              <button key={l.id} type="button" onClick={() => onGoTo(l.id)}
                style={{ ...PJ, borderColor: T.outline, color: T.t2 }}
                className="inline-flex items-center gap-2 h-9 px-2.5 rounded-lg border text-[11.5px] font-bold hover:bg-[#f9fafb]">
                <span className="material-symbols-outlined text-[15px]" style={{ color: T.primary }}>{l.icon}</span>
                {l.label}
              </button>
            ))}
          </div>
        </VizCard>
      </div>
    </div>
  )
}

function Insight({ icon, tone, text }: { icon: string; tone: string; text: React.ReactNode }) {
  return (
    <li className="flex items-start gap-2 text-[11.5px] leading-[1.6]" style={{ color: T.t2 }}>
      <span className="material-symbols-outlined text-[15px] mt-px" style={{ color: tone }}>{icon}</span>
      <span>{text}</span>
    </li>
  )
}
